name: ci

on:
  pull_request:
    branches:
      - main
      - "**"

env:
  CARGO_TERM_COLOR: always
  TOOLCHAIN: stable

jobs:
  ci:
    name: build, test, format, & pre-publish
    timeout-minutes: 10
    runs-on: ubuntu-latest

    # fail on rust warnings
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: update rust
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
      - name: install just
        uses: taiki-e/install-action@just
      - name: build
        run: cargo build --release --verbose
      - name: test
        run: cargo test --verbose
      - name: check formatting
        run: just format --check
      - name: pre-publish
        run: cargo publish --dry-run
